version: "3.9"
services:
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MDB_PASSWORD}
    ports:
      - ${MDB_PORT}:${MDB_PORT}
    volumes:
      - ./_mdb_data:/data/db
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${RDB_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
  webapi:
    image: go-fiber-mongo:0.0.1
    container_name: webapi
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=8080
      - HOST=http://localhost:8080
      - MDB_PORT=27017
      - MDB_USERNAME=root
      - MDB_PASSWORD=passw0rd
      - RDB_PASSWORD=passw0rd
      - APP_ENV=production
      - MDB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - ./uploads:/uploads
    restart: always
    depends_on:
      - db
      - redis
    links:
      - "db:db"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MDB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MDB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
